language: python
python: 2.7
install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/test --layer '!Acceptance'
after_success:
  - bin/coverage.sh
  - pip install -q coveralls
  - coveralls
after_failure:
  - bin/buildout annotate -c travis.cfg
  - firefox -v
notifications:
  irc: irc.freenode.org#plonegovbr
